swagger: '2.0'
info:
  title: EASYPAY API
  description: Test description
  termsOfService: https://www.google.com/policies/terms/
  contact:
    email: contact@snippets.local
  license:
    name: BSD License
  version: v1
host: localhost:8000
schemes:
- http
basePath: /v1/rest
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
security:
- api_key: []
paths:
  /payments/:
    post:
      operationId: payments_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Payment'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Payment'
      tags:
      - payments
    parameters: []
  /payments/{id}/:
    get:
      operationId: payments_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Payment'
      tags:
      - payments
    parameters:
    - name: id
      in: path
      required: true
      type: string
definitions:
  Payment:
    required:
    - provider
    - amount
    - phone_number
    type: object
    properties:
      provider:
        title: Provider
        type: string
        minLength: 1
      amount:
        title: Amount
        type: integer
      phone_number:
        title: Phone number
        type: string
        minLength: 1